<?php
    require_once("c://xampp/htdocs/tech_department/view/head/header.php");
?>
<?php
    require_once("c://xampp/htdocs/tech_department/view/home/home.php");
?>
<?php
    require_once("c://xampp/htdocs/tech_department/view/head/footer.php");
?>