<?php
    require_once("c://xampp/htdocs/web/view/head/header.php");
?>
<?php
    require_once("c://xampp/htdocs/web/view/home/home.php");
?>
<?php
    require_once("c://xampp/htdocs/web/view/head/footer.php");
?>